### PR TITLE
Update koa-cluster

### PR DESCRIPTION
**Pull request by KevinMartin**
Add all harmony features, not just generators.

### CODE REVIEW

**Comment by thelinuxlich** [comment]
this should be accepted for compatibility with io.js

**Comment by jonathanong** [comment]
@thelinuxlich you have been added!!!

**Comment by thelinuxlich** [comment]
Gonna merge this because a long time has passed and it works good with io.js and node 0.12

**Comment by KevinMartin** [comment]
:+1:

**Pull request merged**
